# Generated by Django 3.0.8 on 2020-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
